Teste.BureauVeritas.Presentation.Web/Models/ErrorViewModel.cs
using System;

namespace Teste.BureauVeritas.Presentation.WebAPI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Teste.BureauVeritas.Presentation.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Teste.BureauVeritas.Presentation.WebAPI.Models;

namespace Teste.BureauVeritas.Presentation.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Teste.BureauVeritas.Presentation.Web/Controllers/ProdutoController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Teste.BureauVeritas.Domain.Contracts.AppServices;
using Teste.BureauVeritas.Domain.Contracts.AppServices.Authentication;
using Teste.BureauVeritas.Domain.DTOs;
using Teste.BureauVeritas.Domain.Util.Autenticacao;
using Teste.BureauVeritas.Domain.ViewModels;

namespace Teste.BureauVeritas.Presentation.Web.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly IProdutoAppService _produtoAppService;
        private readonly IAutenticacaoAppService _autenticacaoAppService;
        private readonly IMapper _mapper;

        public ProdutoController(IProdutoAppService produtoAppService, IAutenticacaoAppService autenticacaoAppService,
            IMapper mapper)
        {
            _produtoAppService = produtoAppService;
            _autenticacaoAppService = autenticacaoAppService;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        public PartialViewResult Input()
        {
            return PartialView("_Input");
        }

        [HttpPost]
        [Route("GerarToken")]
        public JsonResult GerarToken()
        {
            Autenticacao autenticacao = _autenticacaoAppService.Autenticar("https://localhost:44361/api/Autenticacao/Login", "POST");
            return Json(autenticacao);
        }

        [HttpPost]
        [Route("ListarProdutos")]
        public PartialViewResult ListarProdutos(string token)
        {
            return PartialView("_GridProdutos", _mapper.Map<IEnumerable<ProdutoDTO>, IEnumerable<ProdutoViewModel>>(_produtoAppService.ObterTodosViaAPI("https://localhost:44361/api/Produto", "GET", token)));
        }
    }
}

Teste.BureauVeritas.Presentation.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Teste.BureauVeritas.Presentation.Web/Views/Produto/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<script>
    var urlGerarToken = '@Url.Action("GerarToken", "Produto")';
    var urlListarProdutos = '@Url.Action("ListarProdutos", "Produto")';
</script>

<script src="~/js/Views/Produto.js"></script>

<div class="row">
    <div class="col-md-12">
        <div id="inputPlaceHolder">
            @{
                Html.RenderPartial("_Input");
            }
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div id="GridProdutos">
            
        </div>
    </div>
</div>

Teste.BureauVeritas.Presentation.Web/Views/Produto/_GridProdutos.cshtml
@model  IEnumerable<Teste.BureauVeritas.Domain.ViewModels.ProdutoViewModel>

    <table class="table table-responsive">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>Descrição</th>
                <th>Categoria</th>
                <th>Preço (R$)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var produto in Model)
            {
                <tr>
                    <td>@produto.ProdutoId</td>
                    <td>@produto.Nome</td>
                    <td>@produto.Descricao</td>
                    <td>@produto.Categoria.Nome</td>
                    <td>@produto.Preco</td>
                </tr>
            }
         </tbody>
    </table>

Teste.BureauVeritas.Presentation.Web/Views/Produto/_Input.cshtml
@model  Teste.BureauVeritas.Domain.Util.Autenticacao.Autenticacao

@{
    ViewData["Title"] = "_Input";
}

<div class="row">
    <div class="col-md-2">
        <button type="button" class="btn btn-success" id="btnGerarToken" onclick="GerarToken();">Gerar token</button>
    </div>
    <div class="col-md-10">
        <div class="row">
            <div class="col-md-2">
                <label>Token:</label>
            </div>
            <div class="col-md-10">
                @Html.TextAreaFor(m => m.Token, new
                {
                    @class = "form-control",
                    autocomplete = "off"
                })
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <label>Expira em:</label>
            </div>
            <div class="col-md-6">
                @Html.TextBoxFor(m => m.Expiration, new
                {
                    @class = "form-control",
                    autocomplete = "off"
                })
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-2">
        <button type="button" class="btn btn-primary" id="btnListarProdutos" onclick="ListarProdutos();">Listar produtos</button>
    </div>
</div>

Teste.BureauVeritas.Presentation.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produtos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>